// megafunction wizard: %RAM: 2-PORT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altsyncram 

// ============================================================
// File Name: ram256.v
// Megafunction Name(s):
// 			altsyncram
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 20.1.0 Build 711 06/05/2020 SJ Lite Edition
// ************************************************************


//Copyright (C) 2020  Intel Corporation. All rights reserved.
//Your use of Intel Corporation's design tools, logic functions 
//and other software and tools, and any partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Intel Program License 
//Subscription Agreement, the Intel Quartus Prime License Agreement,
//the Intel FPGA IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Intel and sold by Intel or its authorized distributors.  Please
//refer to the applicable agreement for further details, at
//https://fpgasoftware.intel.com/eula.


//altsyncram ADDRESS_ACLR_B="NONE" ADDRESS_REG_B="CLOCK0" BYTE_SIZE=8 CLOCK_ENABLE_INPUT_A="BYPASS" CLOCK_ENABLE_INPUT_B="BYPASS" CLOCK_ENABLE_OUTPUT_B="BYPASS" DEVICE_FAMILY="MAX 10" NUMWORDS_A=256 NUMWORDS_B=256 OPERATION_MODE="DUAL_PORT" OUTDATA_ACLR_B="CLEAR0" OUTDATA_REG_B="UNREGISTERED" POWER_UP_UNINITIALIZED="TRUE" RDCONTROL_REG_B="CLOCK0" READ_DURING_WRITE_MODE_MIXED_PORTS="DONT_CARE" WIDTH_A=32 WIDTH_B=32 WIDTH_BYTEENA_A=4 WIDTHAD_A=8 WIDTHAD_B=8 aclr0 address_a address_b byteena_a clock0 data_a q_b rden_b wren_a
//VERSION_BEGIN 20.1 cbx_altera_syncram_nd_impl 2020:06:05:12:04:24:SJ cbx_altsyncram 2020:06:05:12:04:24:SJ cbx_cycloneii 2020:06:05:12:04:24:SJ cbx_lpm_add_sub 2020:06:05:12:04:24:SJ cbx_lpm_compare 2020:06:05:12:04:24:SJ cbx_lpm_decode 2020:06:05:12:04:24:SJ cbx_lpm_mux 2020:06:05:12:04:24:SJ cbx_mgl 2020:06:05:13:25:21:SJ cbx_nadder 2020:06:05:12:04:24:SJ cbx_stratix 2020:06:05:12:04:24:SJ cbx_stratixii 2020:06:05:12:04:24:SJ cbx_stratixiii 2020:06:05:12:04:24:SJ cbx_stratixv 2020:06:05:12:04:24:SJ cbx_util_mgl 2020:06:05:12:04:24:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = M9K 1 reg 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  ram256_altsyncram
	( 
	aclr0,
	address_a,
	address_b,
	byteena_a,
	clock0,
	data_a,
	q_b,
	rden_b,
	wren_a) /* synthesis synthesis_clearbox=1 */;
	input   aclr0;
	input   [7:0]  address_a;
	input   [7:0]  address_b;
	input   [3:0]  byteena_a;
	input   clock0;
	input   [31:0]  data_a;
	output   [31:0]  q_b;
	input   rden_b;
	input   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr0;
	tri1   [7:0]  address_b;
	tri1   [3:0]  byteena_a;
	tri1   clock0;
	tri1   [31:0]  data_a;
	tri1   rden_b;
	tri0   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	rden_b_store;
	wire  [0:0]   wire_ram_block1a_0portbdataout;
	wire  [0:0]   wire_ram_block1a_1portbdataout;
	wire  [0:0]   wire_ram_block1a_2portbdataout;
	wire  [0:0]   wire_ram_block1a_3portbdataout;
	wire  [0:0]   wire_ram_block1a_4portbdataout;
	wire  [0:0]   wire_ram_block1a_5portbdataout;
	wire  [0:0]   wire_ram_block1a_6portbdataout;
	wire  [0:0]   wire_ram_block1a_7portbdataout;
	wire  [0:0]   wire_ram_block1a_8portbdataout;
	wire  [0:0]   wire_ram_block1a_9portbdataout;
	wire  [0:0]   wire_ram_block1a_10portbdataout;
	wire  [0:0]   wire_ram_block1a_11portbdataout;
	wire  [0:0]   wire_ram_block1a_12portbdataout;
	wire  [0:0]   wire_ram_block1a_13portbdataout;
	wire  [0:0]   wire_ram_block1a_14portbdataout;
	wire  [0:0]   wire_ram_block1a_15portbdataout;
	wire  [0:0]   wire_ram_block1a_16portbdataout;
	wire  [0:0]   wire_ram_block1a_17portbdataout;
	wire  [0:0]   wire_ram_block1a_18portbdataout;
	wire  [0:0]   wire_ram_block1a_19portbdataout;
	wire  [0:0]   wire_ram_block1a_20portbdataout;
	wire  [0:0]   wire_ram_block1a_21portbdataout;
	wire  [0:0]   wire_ram_block1a_22portbdataout;
	wire  [0:0]   wire_ram_block1a_23portbdataout;
	wire  [0:0]   wire_ram_block1a_24portbdataout;
	wire  [0:0]   wire_ram_block1a_25portbdataout;
	wire  [0:0]   wire_ram_block1a_26portbdataout;
	wire  [0:0]   wire_ram_block1a_27portbdataout;
	wire  [0:0]   wire_ram_block1a_28portbdataout;
	wire  [0:0]   wire_ram_block1a_29portbdataout;
	wire  [0:0]   wire_ram_block1a_30portbdataout;
	wire  [0:0]   wire_ram_block1a_31portbdataout;
	wire  [7:0]  address_a_wire;
	wire  [7:0]  address_b_wire;

	// synopsys translate_off
	initial
		rden_b_store = 0;
	// synopsys translate_on
	always @ ( posedge clock0)
		  rden_b_store <= rden_b;
	fiftyfivenm_ram_block   ram_block1a_0
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[0]}),
	.portadatain({data_a[0]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_0portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_0.clk0_core_clock_enable = "ena0",
		ram_block1a_0.clk0_input_clock_enable = "none",
		ram_block1a_0.clk1_core_clock_enable = "ena1",
		ram_block1a_0.clk1_input_clock_enable = "none",
		ram_block1a_0.connectivity_checking = "OFF",
		ram_block1a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_0.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_0.operation_mode = "dual_port",
		ram_block1a_0.port_a_address_width = 8,
		ram_block1a_0.port_a_byte_enable_mask_width = 1,
		ram_block1a_0.port_a_byte_size = 1,
		ram_block1a_0.port_a_data_width = 1,
		ram_block1a_0.port_a_first_address = 0,
		ram_block1a_0.port_a_first_bit_number = 0,
		ram_block1a_0.port_a_last_address = 255,
		ram_block1a_0.port_a_logical_ram_depth = 256,
		ram_block1a_0.port_a_logical_ram_width = 32,
		ram_block1a_0.port_b_address_clear = "none",
		ram_block1a_0.port_b_address_clock = "clock1",
		ram_block1a_0.port_b_address_width = 8,
		ram_block1a_0.port_b_data_out_clear = "clear0",
		ram_block1a_0.port_b_data_width = 1,
		ram_block1a_0.port_b_first_address = 0,
		ram_block1a_0.port_b_first_bit_number = 0,
		ram_block1a_0.port_b_last_address = 255,
		ram_block1a_0.port_b_logical_ram_depth = 256,
		ram_block1a_0.port_b_logical_ram_width = 32,
		ram_block1a_0.port_b_read_enable_clock = "clock1",
		ram_block1a_0.power_up_uninitialized = "true",
		ram_block1a_0.ram_block_type = "AUTO",
		ram_block1a_0.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_1
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[0]}),
	.portadatain({data_a[1]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_1portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_1.clk0_core_clock_enable = "ena0",
		ram_block1a_1.clk0_input_clock_enable = "none",
		ram_block1a_1.clk1_core_clock_enable = "ena1",
		ram_block1a_1.clk1_input_clock_enable = "none",
		ram_block1a_1.connectivity_checking = "OFF",
		ram_block1a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_1.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_1.operation_mode = "dual_port",
		ram_block1a_1.port_a_address_width = 8,
		ram_block1a_1.port_a_byte_enable_mask_width = 1,
		ram_block1a_1.port_a_byte_size = 1,
		ram_block1a_1.port_a_data_width = 1,
		ram_block1a_1.port_a_first_address = 0,
		ram_block1a_1.port_a_first_bit_number = 1,
		ram_block1a_1.port_a_last_address = 255,
		ram_block1a_1.port_a_logical_ram_depth = 256,
		ram_block1a_1.port_a_logical_ram_width = 32,
		ram_block1a_1.port_b_address_clear = "none",
		ram_block1a_1.port_b_address_clock = "clock1",
		ram_block1a_1.port_b_address_width = 8,
		ram_block1a_1.port_b_data_out_clear = "clear0",
		ram_block1a_1.port_b_data_width = 1,
		ram_block1a_1.port_b_first_address = 0,
		ram_block1a_1.port_b_first_bit_number = 1,
		ram_block1a_1.port_b_last_address = 255,
		ram_block1a_1.port_b_logical_ram_depth = 256,
		ram_block1a_1.port_b_logical_ram_width = 32,
		ram_block1a_1.port_b_read_enable_clock = "clock1",
		ram_block1a_1.power_up_uninitialized = "true",
		ram_block1a_1.ram_block_type = "AUTO",
		ram_block1a_1.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_2
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[0]}),
	.portadatain({data_a[2]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_2portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_2.clk0_core_clock_enable = "ena0",
		ram_block1a_2.clk0_input_clock_enable = "none",
		ram_block1a_2.clk1_core_clock_enable = "ena1",
		ram_block1a_2.clk1_input_clock_enable = "none",
		ram_block1a_2.connectivity_checking = "OFF",
		ram_block1a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_2.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_2.operation_mode = "dual_port",
		ram_block1a_2.port_a_address_width = 8,
		ram_block1a_2.port_a_byte_enable_mask_width = 1,
		ram_block1a_2.port_a_byte_size = 1,
		ram_block1a_2.port_a_data_width = 1,
		ram_block1a_2.port_a_first_address = 0,
		ram_block1a_2.port_a_first_bit_number = 2,
		ram_block1a_2.port_a_last_address = 255,
		ram_block1a_2.port_a_logical_ram_depth = 256,
		ram_block1a_2.port_a_logical_ram_width = 32,
		ram_block1a_2.port_b_address_clear = "none",
		ram_block1a_2.port_b_address_clock = "clock1",
		ram_block1a_2.port_b_address_width = 8,
		ram_block1a_2.port_b_data_out_clear = "clear0",
		ram_block1a_2.port_b_data_width = 1,
		ram_block1a_2.port_b_first_address = 0,
		ram_block1a_2.port_b_first_bit_number = 2,
		ram_block1a_2.port_b_last_address = 255,
		ram_block1a_2.port_b_logical_ram_depth = 256,
		ram_block1a_2.port_b_logical_ram_width = 32,
		ram_block1a_2.port_b_read_enable_clock = "clock1",
		ram_block1a_2.power_up_uninitialized = "true",
		ram_block1a_2.ram_block_type = "AUTO",
		ram_block1a_2.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_3
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[0]}),
	.portadatain({data_a[3]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_3portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_3.clk0_core_clock_enable = "ena0",
		ram_block1a_3.clk0_input_clock_enable = "none",
		ram_block1a_3.clk1_core_clock_enable = "ena1",
		ram_block1a_3.clk1_input_clock_enable = "none",
		ram_block1a_3.connectivity_checking = "OFF",
		ram_block1a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_3.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_3.operation_mode = "dual_port",
		ram_block1a_3.port_a_address_width = 8,
		ram_block1a_3.port_a_byte_enable_mask_width = 1,
		ram_block1a_3.port_a_byte_size = 1,
		ram_block1a_3.port_a_data_width = 1,
		ram_block1a_3.port_a_first_address = 0,
		ram_block1a_3.port_a_first_bit_number = 3,
		ram_block1a_3.port_a_last_address = 255,
		ram_block1a_3.port_a_logical_ram_depth = 256,
		ram_block1a_3.port_a_logical_ram_width = 32,
		ram_block1a_3.port_b_address_clear = "none",
		ram_block1a_3.port_b_address_clock = "clock1",
		ram_block1a_3.port_b_address_width = 8,
		ram_block1a_3.port_b_data_out_clear = "clear0",
		ram_block1a_3.port_b_data_width = 1,
		ram_block1a_3.port_b_first_address = 0,
		ram_block1a_3.port_b_first_bit_number = 3,
		ram_block1a_3.port_b_last_address = 255,
		ram_block1a_3.port_b_logical_ram_depth = 256,
		ram_block1a_3.port_b_logical_ram_width = 32,
		ram_block1a_3.port_b_read_enable_clock = "clock1",
		ram_block1a_3.power_up_uninitialized = "true",
		ram_block1a_3.ram_block_type = "AUTO",
		ram_block1a_3.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_4
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[0]}),
	.portadatain({data_a[4]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_4portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_4.clk0_core_clock_enable = "ena0",
		ram_block1a_4.clk0_input_clock_enable = "none",
		ram_block1a_4.clk1_core_clock_enable = "ena1",
		ram_block1a_4.clk1_input_clock_enable = "none",
		ram_block1a_4.connectivity_checking = "OFF",
		ram_block1a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_4.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_4.operation_mode = "dual_port",
		ram_block1a_4.port_a_address_width = 8,
		ram_block1a_4.port_a_byte_enable_mask_width = 1,
		ram_block1a_4.port_a_byte_size = 1,
		ram_block1a_4.port_a_data_width = 1,
		ram_block1a_4.port_a_first_address = 0,
		ram_block1a_4.port_a_first_bit_number = 4,
		ram_block1a_4.port_a_last_address = 255,
		ram_block1a_4.port_a_logical_ram_depth = 256,
		ram_block1a_4.port_a_logical_ram_width = 32,
		ram_block1a_4.port_b_address_clear = "none",
		ram_block1a_4.port_b_address_clock = "clock1",
		ram_block1a_4.port_b_address_width = 8,
		ram_block1a_4.port_b_data_out_clear = "clear0",
		ram_block1a_4.port_b_data_width = 1,
		ram_block1a_4.port_b_first_address = 0,
		ram_block1a_4.port_b_first_bit_number = 4,
		ram_block1a_4.port_b_last_address = 255,
		ram_block1a_4.port_b_logical_ram_depth = 256,
		ram_block1a_4.port_b_logical_ram_width = 32,
		ram_block1a_4.port_b_read_enable_clock = "clock1",
		ram_block1a_4.power_up_uninitialized = "true",
		ram_block1a_4.ram_block_type = "AUTO",
		ram_block1a_4.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_5
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[0]}),
	.portadatain({data_a[5]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_5portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_5.clk0_core_clock_enable = "ena0",
		ram_block1a_5.clk0_input_clock_enable = "none",
		ram_block1a_5.clk1_core_clock_enable = "ena1",
		ram_block1a_5.clk1_input_clock_enable = "none",
		ram_block1a_5.connectivity_checking = "OFF",
		ram_block1a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_5.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_5.operation_mode = "dual_port",
		ram_block1a_5.port_a_address_width = 8,
		ram_block1a_5.port_a_byte_enable_mask_width = 1,
		ram_block1a_5.port_a_byte_size = 1,
		ram_block1a_5.port_a_data_width = 1,
		ram_block1a_5.port_a_first_address = 0,
		ram_block1a_5.port_a_first_bit_number = 5,
		ram_block1a_5.port_a_last_address = 255,
		ram_block1a_5.port_a_logical_ram_depth = 256,
		ram_block1a_5.port_a_logical_ram_width = 32,
		ram_block1a_5.port_b_address_clear = "none",
		ram_block1a_5.port_b_address_clock = "clock1",
		ram_block1a_5.port_b_address_width = 8,
		ram_block1a_5.port_b_data_out_clear = "clear0",
		ram_block1a_5.port_b_data_width = 1,
		ram_block1a_5.port_b_first_address = 0,
		ram_block1a_5.port_b_first_bit_number = 5,
		ram_block1a_5.port_b_last_address = 255,
		ram_block1a_5.port_b_logical_ram_depth = 256,
		ram_block1a_5.port_b_logical_ram_width = 32,
		ram_block1a_5.port_b_read_enable_clock = "clock1",
		ram_block1a_5.power_up_uninitialized = "true",
		ram_block1a_5.ram_block_type = "AUTO",
		ram_block1a_5.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_6
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[0]}),
	.portadatain({data_a[6]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_6portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_6.clk0_core_clock_enable = "ena0",
		ram_block1a_6.clk0_input_clock_enable = "none",
		ram_block1a_6.clk1_core_clock_enable = "ena1",
		ram_block1a_6.clk1_input_clock_enable = "none",
		ram_block1a_6.connectivity_checking = "OFF",
		ram_block1a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_6.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_6.operation_mode = "dual_port",
		ram_block1a_6.port_a_address_width = 8,
		ram_block1a_6.port_a_byte_enable_mask_width = 1,
		ram_block1a_6.port_a_byte_size = 1,
		ram_block1a_6.port_a_data_width = 1,
		ram_block1a_6.port_a_first_address = 0,
		ram_block1a_6.port_a_first_bit_number = 6,
		ram_block1a_6.port_a_last_address = 255,
		ram_block1a_6.port_a_logical_ram_depth = 256,
		ram_block1a_6.port_a_logical_ram_width = 32,
		ram_block1a_6.port_b_address_clear = "none",
		ram_block1a_6.port_b_address_clock = "clock1",
		ram_block1a_6.port_b_address_width = 8,
		ram_block1a_6.port_b_data_out_clear = "clear0",
		ram_block1a_6.port_b_data_width = 1,
		ram_block1a_6.port_b_first_address = 0,
		ram_block1a_6.port_b_first_bit_number = 6,
		ram_block1a_6.port_b_last_address = 255,
		ram_block1a_6.port_b_logical_ram_depth = 256,
		ram_block1a_6.port_b_logical_ram_width = 32,
		ram_block1a_6.port_b_read_enable_clock = "clock1",
		ram_block1a_6.power_up_uninitialized = "true",
		ram_block1a_6.ram_block_type = "AUTO",
		ram_block1a_6.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_7
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[0]}),
	.portadatain({data_a[7]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_7portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_7.clk0_core_clock_enable = "ena0",
		ram_block1a_7.clk0_input_clock_enable = "none",
		ram_block1a_7.clk1_core_clock_enable = "ena1",
		ram_block1a_7.clk1_input_clock_enable = "none",
		ram_block1a_7.connectivity_checking = "OFF",
		ram_block1a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_7.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_7.operation_mode = "dual_port",
		ram_block1a_7.port_a_address_width = 8,
		ram_block1a_7.port_a_byte_enable_mask_width = 1,
		ram_block1a_7.port_a_byte_size = 1,
		ram_block1a_7.port_a_data_width = 1,
		ram_block1a_7.port_a_first_address = 0,
		ram_block1a_7.port_a_first_bit_number = 7,
		ram_block1a_7.port_a_last_address = 255,
		ram_block1a_7.port_a_logical_ram_depth = 256,
		ram_block1a_7.port_a_logical_ram_width = 32,
		ram_block1a_7.port_b_address_clear = "none",
		ram_block1a_7.port_b_address_clock = "clock1",
		ram_block1a_7.port_b_address_width = 8,
		ram_block1a_7.port_b_data_out_clear = "clear0",
		ram_block1a_7.port_b_data_width = 1,
		ram_block1a_7.port_b_first_address = 0,
		ram_block1a_7.port_b_first_bit_number = 7,
		ram_block1a_7.port_b_last_address = 255,
		ram_block1a_7.port_b_logical_ram_depth = 256,
		ram_block1a_7.port_b_logical_ram_width = 32,
		ram_block1a_7.port_b_read_enable_clock = "clock1",
		ram_block1a_7.power_up_uninitialized = "true",
		ram_block1a_7.ram_block_type = "AUTO",
		ram_block1a_7.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_8
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[1]}),
	.portadatain({data_a[8]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_8portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_8.clk0_core_clock_enable = "ena0",
		ram_block1a_8.clk0_input_clock_enable = "none",
		ram_block1a_8.clk1_core_clock_enable = "ena1",
		ram_block1a_8.clk1_input_clock_enable = "none",
		ram_block1a_8.connectivity_checking = "OFF",
		ram_block1a_8.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_8.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_8.operation_mode = "dual_port",
		ram_block1a_8.port_a_address_width = 8,
		ram_block1a_8.port_a_byte_enable_mask_width = 1,
		ram_block1a_8.port_a_byte_size = 1,
		ram_block1a_8.port_a_data_width = 1,
		ram_block1a_8.port_a_first_address = 0,
		ram_block1a_8.port_a_first_bit_number = 8,
		ram_block1a_8.port_a_last_address = 255,
		ram_block1a_8.port_a_logical_ram_depth = 256,
		ram_block1a_8.port_a_logical_ram_width = 32,
		ram_block1a_8.port_b_address_clear = "none",
		ram_block1a_8.port_b_address_clock = "clock1",
		ram_block1a_8.port_b_address_width = 8,
		ram_block1a_8.port_b_data_out_clear = "clear0",
		ram_block1a_8.port_b_data_width = 1,
		ram_block1a_8.port_b_first_address = 0,
		ram_block1a_8.port_b_first_bit_number = 8,
		ram_block1a_8.port_b_last_address = 255,
		ram_block1a_8.port_b_logical_ram_depth = 256,
		ram_block1a_8.port_b_logical_ram_width = 32,
		ram_block1a_8.port_b_read_enable_clock = "clock1",
		ram_block1a_8.power_up_uninitialized = "true",
		ram_block1a_8.ram_block_type = "AUTO",
		ram_block1a_8.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_9
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[1]}),
	.portadatain({data_a[9]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_9portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_9.clk0_core_clock_enable = "ena0",
		ram_block1a_9.clk0_input_clock_enable = "none",
		ram_block1a_9.clk1_core_clock_enable = "ena1",
		ram_block1a_9.clk1_input_clock_enable = "none",
		ram_block1a_9.connectivity_checking = "OFF",
		ram_block1a_9.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_9.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_9.operation_mode = "dual_port",
		ram_block1a_9.port_a_address_width = 8,
		ram_block1a_9.port_a_byte_enable_mask_width = 1,
		ram_block1a_9.port_a_byte_size = 1,
		ram_block1a_9.port_a_data_width = 1,
		ram_block1a_9.port_a_first_address = 0,
		ram_block1a_9.port_a_first_bit_number = 9,
		ram_block1a_9.port_a_last_address = 255,
		ram_block1a_9.port_a_logical_ram_depth = 256,
		ram_block1a_9.port_a_logical_ram_width = 32,
		ram_block1a_9.port_b_address_clear = "none",
		ram_block1a_9.port_b_address_clock = "clock1",
		ram_block1a_9.port_b_address_width = 8,
		ram_block1a_9.port_b_data_out_clear = "clear0",
		ram_block1a_9.port_b_data_width = 1,
		ram_block1a_9.port_b_first_address = 0,
		ram_block1a_9.port_b_first_bit_number = 9,
		ram_block1a_9.port_b_last_address = 255,
		ram_block1a_9.port_b_logical_ram_depth = 256,
		ram_block1a_9.port_b_logical_ram_width = 32,
		ram_block1a_9.port_b_read_enable_clock = "clock1",
		ram_block1a_9.power_up_uninitialized = "true",
		ram_block1a_9.ram_block_type = "AUTO",
		ram_block1a_9.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_10
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[1]}),
	.portadatain({data_a[10]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_10portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_10.clk0_core_clock_enable = "ena0",
		ram_block1a_10.clk0_input_clock_enable = "none",
		ram_block1a_10.clk1_core_clock_enable = "ena1",
		ram_block1a_10.clk1_input_clock_enable = "none",
		ram_block1a_10.connectivity_checking = "OFF",
		ram_block1a_10.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_10.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_10.operation_mode = "dual_port",
		ram_block1a_10.port_a_address_width = 8,
		ram_block1a_10.port_a_byte_enable_mask_width = 1,
		ram_block1a_10.port_a_byte_size = 1,
		ram_block1a_10.port_a_data_width = 1,
		ram_block1a_10.port_a_first_address = 0,
		ram_block1a_10.port_a_first_bit_number = 10,
		ram_block1a_10.port_a_last_address = 255,
		ram_block1a_10.port_a_logical_ram_depth = 256,
		ram_block1a_10.port_a_logical_ram_width = 32,
		ram_block1a_10.port_b_address_clear = "none",
		ram_block1a_10.port_b_address_clock = "clock1",
		ram_block1a_10.port_b_address_width = 8,
		ram_block1a_10.port_b_data_out_clear = "clear0",
		ram_block1a_10.port_b_data_width = 1,
		ram_block1a_10.port_b_first_address = 0,
		ram_block1a_10.port_b_first_bit_number = 10,
		ram_block1a_10.port_b_last_address = 255,
		ram_block1a_10.port_b_logical_ram_depth = 256,
		ram_block1a_10.port_b_logical_ram_width = 32,
		ram_block1a_10.port_b_read_enable_clock = "clock1",
		ram_block1a_10.power_up_uninitialized = "true",
		ram_block1a_10.ram_block_type = "AUTO",
		ram_block1a_10.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_11
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[1]}),
	.portadatain({data_a[11]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_11portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_11.clk0_core_clock_enable = "ena0",
		ram_block1a_11.clk0_input_clock_enable = "none",
		ram_block1a_11.clk1_core_clock_enable = "ena1",
		ram_block1a_11.clk1_input_clock_enable = "none",
		ram_block1a_11.connectivity_checking = "OFF",
		ram_block1a_11.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_11.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_11.operation_mode = "dual_port",
		ram_block1a_11.port_a_address_width = 8,
		ram_block1a_11.port_a_byte_enable_mask_width = 1,
		ram_block1a_11.port_a_byte_size = 1,
		ram_block1a_11.port_a_data_width = 1,
		ram_block1a_11.port_a_first_address = 0,
		ram_block1a_11.port_a_first_bit_number = 11,
		ram_block1a_11.port_a_last_address = 255,
		ram_block1a_11.port_a_logical_ram_depth = 256,
		ram_block1a_11.port_a_logical_ram_width = 32,
		ram_block1a_11.port_b_address_clear = "none",
		ram_block1a_11.port_b_address_clock = "clock1",
		ram_block1a_11.port_b_address_width = 8,
		ram_block1a_11.port_b_data_out_clear = "clear0",
		ram_block1a_11.port_b_data_width = 1,
		ram_block1a_11.port_b_first_address = 0,
		ram_block1a_11.port_b_first_bit_number = 11,
		ram_block1a_11.port_b_last_address = 255,
		ram_block1a_11.port_b_logical_ram_depth = 256,
		ram_block1a_11.port_b_logical_ram_width = 32,
		ram_block1a_11.port_b_read_enable_clock = "clock1",
		ram_block1a_11.power_up_uninitialized = "true",
		ram_block1a_11.ram_block_type = "AUTO",
		ram_block1a_11.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_12
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[1]}),
	.portadatain({data_a[12]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_12portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_12.clk0_core_clock_enable = "ena0",
		ram_block1a_12.clk0_input_clock_enable = "none",
		ram_block1a_12.clk1_core_clock_enable = "ena1",
		ram_block1a_12.clk1_input_clock_enable = "none",
		ram_block1a_12.connectivity_checking = "OFF",
		ram_block1a_12.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_12.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_12.operation_mode = "dual_port",
		ram_block1a_12.port_a_address_width = 8,
		ram_block1a_12.port_a_byte_enable_mask_width = 1,
		ram_block1a_12.port_a_byte_size = 1,
		ram_block1a_12.port_a_data_width = 1,
		ram_block1a_12.port_a_first_address = 0,
		ram_block1a_12.port_a_first_bit_number = 12,
		ram_block1a_12.port_a_last_address = 255,
		ram_block1a_12.port_a_logical_ram_depth = 256,
		ram_block1a_12.port_a_logical_ram_width = 32,
		ram_block1a_12.port_b_address_clear = "none",
		ram_block1a_12.port_b_address_clock = "clock1",
		ram_block1a_12.port_b_address_width = 8,
		ram_block1a_12.port_b_data_out_clear = "clear0",
		ram_block1a_12.port_b_data_width = 1,
		ram_block1a_12.port_b_first_address = 0,
		ram_block1a_12.port_b_first_bit_number = 12,
		ram_block1a_12.port_b_last_address = 255,
		ram_block1a_12.port_b_logical_ram_depth = 256,
		ram_block1a_12.port_b_logical_ram_width = 32,
		ram_block1a_12.port_b_read_enable_clock = "clock1",
		ram_block1a_12.power_up_uninitialized = "true",
		ram_block1a_12.ram_block_type = "AUTO",
		ram_block1a_12.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_13
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[1]}),
	.portadatain({data_a[13]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_13portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_13.clk0_core_clock_enable = "ena0",
		ram_block1a_13.clk0_input_clock_enable = "none",
		ram_block1a_13.clk1_core_clock_enable = "ena1",
		ram_block1a_13.clk1_input_clock_enable = "none",
		ram_block1a_13.connectivity_checking = "OFF",
		ram_block1a_13.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_13.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_13.operation_mode = "dual_port",
		ram_block1a_13.port_a_address_width = 8,
		ram_block1a_13.port_a_byte_enable_mask_width = 1,
		ram_block1a_13.port_a_byte_size = 1,
		ram_block1a_13.port_a_data_width = 1,
		ram_block1a_13.port_a_first_address = 0,
		ram_block1a_13.port_a_first_bit_number = 13,
		ram_block1a_13.port_a_last_address = 255,
		ram_block1a_13.port_a_logical_ram_depth = 256,
		ram_block1a_13.port_a_logical_ram_width = 32,
		ram_block1a_13.port_b_address_clear = "none",
		ram_block1a_13.port_b_address_clock = "clock1",
		ram_block1a_13.port_b_address_width = 8,
		ram_block1a_13.port_b_data_out_clear = "clear0",
		ram_block1a_13.port_b_data_width = 1,
		ram_block1a_13.port_b_first_address = 0,
		ram_block1a_13.port_b_first_bit_number = 13,
		ram_block1a_13.port_b_last_address = 255,
		ram_block1a_13.port_b_logical_ram_depth = 256,
		ram_block1a_13.port_b_logical_ram_width = 32,
		ram_block1a_13.port_b_read_enable_clock = "clock1",
		ram_block1a_13.power_up_uninitialized = "true",
		ram_block1a_13.ram_block_type = "AUTO",
		ram_block1a_13.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_14
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[1]}),
	.portadatain({data_a[14]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_14portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_14.clk0_core_clock_enable = "ena0",
		ram_block1a_14.clk0_input_clock_enable = "none",
		ram_block1a_14.clk1_core_clock_enable = "ena1",
		ram_block1a_14.clk1_input_clock_enable = "none",
		ram_block1a_14.connectivity_checking = "OFF",
		ram_block1a_14.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_14.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_14.operation_mode = "dual_port",
		ram_block1a_14.port_a_address_width = 8,
		ram_block1a_14.port_a_byte_enable_mask_width = 1,
		ram_block1a_14.port_a_byte_size = 1,
		ram_block1a_14.port_a_data_width = 1,
		ram_block1a_14.port_a_first_address = 0,
		ram_block1a_14.port_a_first_bit_number = 14,
		ram_block1a_14.port_a_last_address = 255,
		ram_block1a_14.port_a_logical_ram_depth = 256,
		ram_block1a_14.port_a_logical_ram_width = 32,
		ram_block1a_14.port_b_address_clear = "none",
		ram_block1a_14.port_b_address_clock = "clock1",
		ram_block1a_14.port_b_address_width = 8,
		ram_block1a_14.port_b_data_out_clear = "clear0",
		ram_block1a_14.port_b_data_width = 1,
		ram_block1a_14.port_b_first_address = 0,
		ram_block1a_14.port_b_first_bit_number = 14,
		ram_block1a_14.port_b_last_address = 255,
		ram_block1a_14.port_b_logical_ram_depth = 256,
		ram_block1a_14.port_b_logical_ram_width = 32,
		ram_block1a_14.port_b_read_enable_clock = "clock1",
		ram_block1a_14.power_up_uninitialized = "true",
		ram_block1a_14.ram_block_type = "AUTO",
		ram_block1a_14.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_15
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[1]}),
	.portadatain({data_a[15]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_15portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_15.clk0_core_clock_enable = "ena0",
		ram_block1a_15.clk0_input_clock_enable = "none",
		ram_block1a_15.clk1_core_clock_enable = "ena1",
		ram_block1a_15.clk1_input_clock_enable = "none",
		ram_block1a_15.connectivity_checking = "OFF",
		ram_block1a_15.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_15.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_15.operation_mode = "dual_port",
		ram_block1a_15.port_a_address_width = 8,
		ram_block1a_15.port_a_byte_enable_mask_width = 1,
		ram_block1a_15.port_a_byte_size = 1,
		ram_block1a_15.port_a_data_width = 1,
		ram_block1a_15.port_a_first_address = 0,
		ram_block1a_15.port_a_first_bit_number = 15,
		ram_block1a_15.port_a_last_address = 255,
		ram_block1a_15.port_a_logical_ram_depth = 256,
		ram_block1a_15.port_a_logical_ram_width = 32,
		ram_block1a_15.port_b_address_clear = "none",
		ram_block1a_15.port_b_address_clock = "clock1",
		ram_block1a_15.port_b_address_width = 8,
		ram_block1a_15.port_b_data_out_clear = "clear0",
		ram_block1a_15.port_b_data_width = 1,
		ram_block1a_15.port_b_first_address = 0,
		ram_block1a_15.port_b_first_bit_number = 15,
		ram_block1a_15.port_b_last_address = 255,
		ram_block1a_15.port_b_logical_ram_depth = 256,
		ram_block1a_15.port_b_logical_ram_width = 32,
		ram_block1a_15.port_b_read_enable_clock = "clock1",
		ram_block1a_15.power_up_uninitialized = "true",
		ram_block1a_15.ram_block_type = "AUTO",
		ram_block1a_15.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_16
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[2]}),
	.portadatain({data_a[16]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_16portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_16.clk0_core_clock_enable = "ena0",
		ram_block1a_16.clk0_input_clock_enable = "none",
		ram_block1a_16.clk1_core_clock_enable = "ena1",
		ram_block1a_16.clk1_input_clock_enable = "none",
		ram_block1a_16.connectivity_checking = "OFF",
		ram_block1a_16.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_16.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_16.operation_mode = "dual_port",
		ram_block1a_16.port_a_address_width = 8,
		ram_block1a_16.port_a_byte_enable_mask_width = 1,
		ram_block1a_16.port_a_byte_size = 1,
		ram_block1a_16.port_a_data_width = 1,
		ram_block1a_16.port_a_first_address = 0,
		ram_block1a_16.port_a_first_bit_number = 16,
		ram_block1a_16.port_a_last_address = 255,
		ram_block1a_16.port_a_logical_ram_depth = 256,
		ram_block1a_16.port_a_logical_ram_width = 32,
		ram_block1a_16.port_b_address_clear = "none",
		ram_block1a_16.port_b_address_clock = "clock1",
		ram_block1a_16.port_b_address_width = 8,
		ram_block1a_16.port_b_data_out_clear = "clear0",
		ram_block1a_16.port_b_data_width = 1,
		ram_block1a_16.port_b_first_address = 0,
		ram_block1a_16.port_b_first_bit_number = 16,
		ram_block1a_16.port_b_last_address = 255,
		ram_block1a_16.port_b_logical_ram_depth = 256,
		ram_block1a_16.port_b_logical_ram_width = 32,
		ram_block1a_16.port_b_read_enable_clock = "clock1",
		ram_block1a_16.power_up_uninitialized = "true",
		ram_block1a_16.ram_block_type = "AUTO",
		ram_block1a_16.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_17
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[2]}),
	.portadatain({data_a[17]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_17portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_17.clk0_core_clock_enable = "ena0",
		ram_block1a_17.clk0_input_clock_enable = "none",
		ram_block1a_17.clk1_core_clock_enable = "ena1",
		ram_block1a_17.clk1_input_clock_enable = "none",
		ram_block1a_17.connectivity_checking = "OFF",
		ram_block1a_17.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_17.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_17.operation_mode = "dual_port",
		ram_block1a_17.port_a_address_width = 8,
		ram_block1a_17.port_a_byte_enable_mask_width = 1,
		ram_block1a_17.port_a_byte_size = 1,
		ram_block1a_17.port_a_data_width = 1,
		ram_block1a_17.port_a_first_address = 0,
		ram_block1a_17.port_a_first_bit_number = 17,
		ram_block1a_17.port_a_last_address = 255,
		ram_block1a_17.port_a_logical_ram_depth = 256,
		ram_block1a_17.port_a_logical_ram_width = 32,
		ram_block1a_17.port_b_address_clear = "none",
		ram_block1a_17.port_b_address_clock = "clock1",
		ram_block1a_17.port_b_address_width = 8,
		ram_block1a_17.port_b_data_out_clear = "clear0",
		ram_block1a_17.port_b_data_width = 1,
		ram_block1a_17.port_b_first_address = 0,
		ram_block1a_17.port_b_first_bit_number = 17,
		ram_block1a_17.port_b_last_address = 255,
		ram_block1a_17.port_b_logical_ram_depth = 256,
		ram_block1a_17.port_b_logical_ram_width = 32,
		ram_block1a_17.port_b_read_enable_clock = "clock1",
		ram_block1a_17.power_up_uninitialized = "true",
		ram_block1a_17.ram_block_type = "AUTO",
		ram_block1a_17.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_18
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[2]}),
	.portadatain({data_a[18]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_18portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_18.clk0_core_clock_enable = "ena0",
		ram_block1a_18.clk0_input_clock_enable = "none",
		ram_block1a_18.clk1_core_clock_enable = "ena1",
		ram_block1a_18.clk1_input_clock_enable = "none",
		ram_block1a_18.connectivity_checking = "OFF",
		ram_block1a_18.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_18.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_18.operation_mode = "dual_port",
		ram_block1a_18.port_a_address_width = 8,
		ram_block1a_18.port_a_byte_enable_mask_width = 1,
		ram_block1a_18.port_a_byte_size = 1,
		ram_block1a_18.port_a_data_width = 1,
		ram_block1a_18.port_a_first_address = 0,
		ram_block1a_18.port_a_first_bit_number = 18,
		ram_block1a_18.port_a_last_address = 255,
		ram_block1a_18.port_a_logical_ram_depth = 256,
		ram_block1a_18.port_a_logical_ram_width = 32,
		ram_block1a_18.port_b_address_clear = "none",
		ram_block1a_18.port_b_address_clock = "clock1",
		ram_block1a_18.port_b_address_width = 8,
		ram_block1a_18.port_b_data_out_clear = "clear0",
		ram_block1a_18.port_b_data_width = 1,
		ram_block1a_18.port_b_first_address = 0,
		ram_block1a_18.port_b_first_bit_number = 18,
		ram_block1a_18.port_b_last_address = 255,
		ram_block1a_18.port_b_logical_ram_depth = 256,
		ram_block1a_18.port_b_logical_ram_width = 32,
		ram_block1a_18.port_b_read_enable_clock = "clock1",
		ram_block1a_18.power_up_uninitialized = "true",
		ram_block1a_18.ram_block_type = "AUTO",
		ram_block1a_18.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_19
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[2]}),
	.portadatain({data_a[19]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_19portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_19.clk0_core_clock_enable = "ena0",
		ram_block1a_19.clk0_input_clock_enable = "none",
		ram_block1a_19.clk1_core_clock_enable = "ena1",
		ram_block1a_19.clk1_input_clock_enable = "none",
		ram_block1a_19.connectivity_checking = "OFF",
		ram_block1a_19.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_19.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_19.operation_mode = "dual_port",
		ram_block1a_19.port_a_address_width = 8,
		ram_block1a_19.port_a_byte_enable_mask_width = 1,
		ram_block1a_19.port_a_byte_size = 1,
		ram_block1a_19.port_a_data_width = 1,
		ram_block1a_19.port_a_first_address = 0,
		ram_block1a_19.port_a_first_bit_number = 19,
		ram_block1a_19.port_a_last_address = 255,
		ram_block1a_19.port_a_logical_ram_depth = 256,
		ram_block1a_19.port_a_logical_ram_width = 32,
		ram_block1a_19.port_b_address_clear = "none",
		ram_block1a_19.port_b_address_clock = "clock1",
		ram_block1a_19.port_b_address_width = 8,
		ram_block1a_19.port_b_data_out_clear = "clear0",
		ram_block1a_19.port_b_data_width = 1,
		ram_block1a_19.port_b_first_address = 0,
		ram_block1a_19.port_b_first_bit_number = 19,
		ram_block1a_19.port_b_last_address = 255,
		ram_block1a_19.port_b_logical_ram_depth = 256,
		ram_block1a_19.port_b_logical_ram_width = 32,
		ram_block1a_19.port_b_read_enable_clock = "clock1",
		ram_block1a_19.power_up_uninitialized = "true",
		ram_block1a_19.ram_block_type = "AUTO",
		ram_block1a_19.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_20
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[2]}),
	.portadatain({data_a[20]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_20portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_20.clk0_core_clock_enable = "ena0",
		ram_block1a_20.clk0_input_clock_enable = "none",
		ram_block1a_20.clk1_core_clock_enable = "ena1",
		ram_block1a_20.clk1_input_clock_enable = "none",
		ram_block1a_20.connectivity_checking = "OFF",
		ram_block1a_20.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_20.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_20.operation_mode = "dual_port",
		ram_block1a_20.port_a_address_width = 8,
		ram_block1a_20.port_a_byte_enable_mask_width = 1,
		ram_block1a_20.port_a_byte_size = 1,
		ram_block1a_20.port_a_data_width = 1,
		ram_block1a_20.port_a_first_address = 0,
		ram_block1a_20.port_a_first_bit_number = 20,
		ram_block1a_20.port_a_last_address = 255,
		ram_block1a_20.port_a_logical_ram_depth = 256,
		ram_block1a_20.port_a_logical_ram_width = 32,
		ram_block1a_20.port_b_address_clear = "none",
		ram_block1a_20.port_b_address_clock = "clock1",
		ram_block1a_20.port_b_address_width = 8,
		ram_block1a_20.port_b_data_out_clear = "clear0",
		ram_block1a_20.port_b_data_width = 1,
		ram_block1a_20.port_b_first_address = 0,
		ram_block1a_20.port_b_first_bit_number = 20,
		ram_block1a_20.port_b_last_address = 255,
		ram_block1a_20.port_b_logical_ram_depth = 256,
		ram_block1a_20.port_b_logical_ram_width = 32,
		ram_block1a_20.port_b_read_enable_clock = "clock1",
		ram_block1a_20.power_up_uninitialized = "true",
		ram_block1a_20.ram_block_type = "AUTO",
		ram_block1a_20.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_21
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[2]}),
	.portadatain({data_a[21]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_21portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_21.clk0_core_clock_enable = "ena0",
		ram_block1a_21.clk0_input_clock_enable = "none",
		ram_block1a_21.clk1_core_clock_enable = "ena1",
		ram_block1a_21.clk1_input_clock_enable = "none",
		ram_block1a_21.connectivity_checking = "OFF",
		ram_block1a_21.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_21.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_21.operation_mode = "dual_port",
		ram_block1a_21.port_a_address_width = 8,
		ram_block1a_21.port_a_byte_enable_mask_width = 1,
		ram_block1a_21.port_a_byte_size = 1,
		ram_block1a_21.port_a_data_width = 1,
		ram_block1a_21.port_a_first_address = 0,
		ram_block1a_21.port_a_first_bit_number = 21,
		ram_block1a_21.port_a_last_address = 255,
		ram_block1a_21.port_a_logical_ram_depth = 256,
		ram_block1a_21.port_a_logical_ram_width = 32,
		ram_block1a_21.port_b_address_clear = "none",
		ram_block1a_21.port_b_address_clock = "clock1",
		ram_block1a_21.port_b_address_width = 8,
		ram_block1a_21.port_b_data_out_clear = "clear0",
		ram_block1a_21.port_b_data_width = 1,
		ram_block1a_21.port_b_first_address = 0,
		ram_block1a_21.port_b_first_bit_number = 21,
		ram_block1a_21.port_b_last_address = 255,
		ram_block1a_21.port_b_logical_ram_depth = 256,
		ram_block1a_21.port_b_logical_ram_width = 32,
		ram_block1a_21.port_b_read_enable_clock = "clock1",
		ram_block1a_21.power_up_uninitialized = "true",
		ram_block1a_21.ram_block_type = "AUTO",
		ram_block1a_21.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_22
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[2]}),
	.portadatain({data_a[22]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_22portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_22.clk0_core_clock_enable = "ena0",
		ram_block1a_22.clk0_input_clock_enable = "none",
		ram_block1a_22.clk1_core_clock_enable = "ena1",
		ram_block1a_22.clk1_input_clock_enable = "none",
		ram_block1a_22.connectivity_checking = "OFF",
		ram_block1a_22.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_22.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_22.operation_mode = "dual_port",
		ram_block1a_22.port_a_address_width = 8,
		ram_block1a_22.port_a_byte_enable_mask_width = 1,
		ram_block1a_22.port_a_byte_size = 1,
		ram_block1a_22.port_a_data_width = 1,
		ram_block1a_22.port_a_first_address = 0,
		ram_block1a_22.port_a_first_bit_number = 22,
		ram_block1a_22.port_a_last_address = 255,
		ram_block1a_22.port_a_logical_ram_depth = 256,
		ram_block1a_22.port_a_logical_ram_width = 32,
		ram_block1a_22.port_b_address_clear = "none",
		ram_block1a_22.port_b_address_clock = "clock1",
		ram_block1a_22.port_b_address_width = 8,
		ram_block1a_22.port_b_data_out_clear = "clear0",
		ram_block1a_22.port_b_data_width = 1,
		ram_block1a_22.port_b_first_address = 0,
		ram_block1a_22.port_b_first_bit_number = 22,
		ram_block1a_22.port_b_last_address = 255,
		ram_block1a_22.port_b_logical_ram_depth = 256,
		ram_block1a_22.port_b_logical_ram_width = 32,
		ram_block1a_22.port_b_read_enable_clock = "clock1",
		ram_block1a_22.power_up_uninitialized = "true",
		ram_block1a_22.ram_block_type = "AUTO",
		ram_block1a_22.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_23
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[2]}),
	.portadatain({data_a[23]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_23portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_23.clk0_core_clock_enable = "ena0",
		ram_block1a_23.clk0_input_clock_enable = "none",
		ram_block1a_23.clk1_core_clock_enable = "ena1",
		ram_block1a_23.clk1_input_clock_enable = "none",
		ram_block1a_23.connectivity_checking = "OFF",
		ram_block1a_23.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_23.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_23.operation_mode = "dual_port",
		ram_block1a_23.port_a_address_width = 8,
		ram_block1a_23.port_a_byte_enable_mask_width = 1,
		ram_block1a_23.port_a_byte_size = 1,
		ram_block1a_23.port_a_data_width = 1,
		ram_block1a_23.port_a_first_address = 0,
		ram_block1a_23.port_a_first_bit_number = 23,
		ram_block1a_23.port_a_last_address = 255,
		ram_block1a_23.port_a_logical_ram_depth = 256,
		ram_block1a_23.port_a_logical_ram_width = 32,
		ram_block1a_23.port_b_address_clear = "none",
		ram_block1a_23.port_b_address_clock = "clock1",
		ram_block1a_23.port_b_address_width = 8,
		ram_block1a_23.port_b_data_out_clear = "clear0",
		ram_block1a_23.port_b_data_width = 1,
		ram_block1a_23.port_b_first_address = 0,
		ram_block1a_23.port_b_first_bit_number = 23,
		ram_block1a_23.port_b_last_address = 255,
		ram_block1a_23.port_b_logical_ram_depth = 256,
		ram_block1a_23.port_b_logical_ram_width = 32,
		ram_block1a_23.port_b_read_enable_clock = "clock1",
		ram_block1a_23.power_up_uninitialized = "true",
		ram_block1a_23.ram_block_type = "AUTO",
		ram_block1a_23.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_24
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[3]}),
	.portadatain({data_a[24]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_24portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_24.clk0_core_clock_enable = "ena0",
		ram_block1a_24.clk0_input_clock_enable = "none",
		ram_block1a_24.clk1_core_clock_enable = "ena1",
		ram_block1a_24.clk1_input_clock_enable = "none",
		ram_block1a_24.connectivity_checking = "OFF",
		ram_block1a_24.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_24.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_24.operation_mode = "dual_port",
		ram_block1a_24.port_a_address_width = 8,
		ram_block1a_24.port_a_byte_enable_mask_width = 1,
		ram_block1a_24.port_a_byte_size = 1,
		ram_block1a_24.port_a_data_width = 1,
		ram_block1a_24.port_a_first_address = 0,
		ram_block1a_24.port_a_first_bit_number = 24,
		ram_block1a_24.port_a_last_address = 255,
		ram_block1a_24.port_a_logical_ram_depth = 256,
		ram_block1a_24.port_a_logical_ram_width = 32,
		ram_block1a_24.port_b_address_clear = "none",
		ram_block1a_24.port_b_address_clock = "clock1",
		ram_block1a_24.port_b_address_width = 8,
		ram_block1a_24.port_b_data_out_clear = "clear0",
		ram_block1a_24.port_b_data_width = 1,
		ram_block1a_24.port_b_first_address = 0,
		ram_block1a_24.port_b_first_bit_number = 24,
		ram_block1a_24.port_b_last_address = 255,
		ram_block1a_24.port_b_logical_ram_depth = 256,
		ram_block1a_24.port_b_logical_ram_width = 32,
		ram_block1a_24.port_b_read_enable_clock = "clock1",
		ram_block1a_24.power_up_uninitialized = "true",
		ram_block1a_24.ram_block_type = "AUTO",
		ram_block1a_24.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_25
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[3]}),
	.portadatain({data_a[25]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_25portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_25.clk0_core_clock_enable = "ena0",
		ram_block1a_25.clk0_input_clock_enable = "none",
		ram_block1a_25.clk1_core_clock_enable = "ena1",
		ram_block1a_25.clk1_input_clock_enable = "none",
		ram_block1a_25.connectivity_checking = "OFF",
		ram_block1a_25.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_25.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_25.operation_mode = "dual_port",
		ram_block1a_25.port_a_address_width = 8,
		ram_block1a_25.port_a_byte_enable_mask_width = 1,
		ram_block1a_25.port_a_byte_size = 1,
		ram_block1a_25.port_a_data_width = 1,
		ram_block1a_25.port_a_first_address = 0,
		ram_block1a_25.port_a_first_bit_number = 25,
		ram_block1a_25.port_a_last_address = 255,
		ram_block1a_25.port_a_logical_ram_depth = 256,
		ram_block1a_25.port_a_logical_ram_width = 32,
		ram_block1a_25.port_b_address_clear = "none",
		ram_block1a_25.port_b_address_clock = "clock1",
		ram_block1a_25.port_b_address_width = 8,
		ram_block1a_25.port_b_data_out_clear = "clear0",
		ram_block1a_25.port_b_data_width = 1,
		ram_block1a_25.port_b_first_address = 0,
		ram_block1a_25.port_b_first_bit_number = 25,
		ram_block1a_25.port_b_last_address = 255,
		ram_block1a_25.port_b_logical_ram_depth = 256,
		ram_block1a_25.port_b_logical_ram_width = 32,
		ram_block1a_25.port_b_read_enable_clock = "clock1",
		ram_block1a_25.power_up_uninitialized = "true",
		ram_block1a_25.ram_block_type = "AUTO",
		ram_block1a_25.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_26
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[3]}),
	.portadatain({data_a[26]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_26portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_26.clk0_core_clock_enable = "ena0",
		ram_block1a_26.clk0_input_clock_enable = "none",
		ram_block1a_26.clk1_core_clock_enable = "ena1",
		ram_block1a_26.clk1_input_clock_enable = "none",
		ram_block1a_26.connectivity_checking = "OFF",
		ram_block1a_26.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_26.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_26.operation_mode = "dual_port",
		ram_block1a_26.port_a_address_width = 8,
		ram_block1a_26.port_a_byte_enable_mask_width = 1,
		ram_block1a_26.port_a_byte_size = 1,
		ram_block1a_26.port_a_data_width = 1,
		ram_block1a_26.port_a_first_address = 0,
		ram_block1a_26.port_a_first_bit_number = 26,
		ram_block1a_26.port_a_last_address = 255,
		ram_block1a_26.port_a_logical_ram_depth = 256,
		ram_block1a_26.port_a_logical_ram_width = 32,
		ram_block1a_26.port_b_address_clear = "none",
		ram_block1a_26.port_b_address_clock = "clock1",
		ram_block1a_26.port_b_address_width = 8,
		ram_block1a_26.port_b_data_out_clear = "clear0",
		ram_block1a_26.port_b_data_width = 1,
		ram_block1a_26.port_b_first_address = 0,
		ram_block1a_26.port_b_first_bit_number = 26,
		ram_block1a_26.port_b_last_address = 255,
		ram_block1a_26.port_b_logical_ram_depth = 256,
		ram_block1a_26.port_b_logical_ram_width = 32,
		ram_block1a_26.port_b_read_enable_clock = "clock1",
		ram_block1a_26.power_up_uninitialized = "true",
		ram_block1a_26.ram_block_type = "AUTO",
		ram_block1a_26.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_27
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[3]}),
	.portadatain({data_a[27]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_27portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_27.clk0_core_clock_enable = "ena0",
		ram_block1a_27.clk0_input_clock_enable = "none",
		ram_block1a_27.clk1_core_clock_enable = "ena1",
		ram_block1a_27.clk1_input_clock_enable = "none",
		ram_block1a_27.connectivity_checking = "OFF",
		ram_block1a_27.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_27.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_27.operation_mode = "dual_port",
		ram_block1a_27.port_a_address_width = 8,
		ram_block1a_27.port_a_byte_enable_mask_width = 1,
		ram_block1a_27.port_a_byte_size = 1,
		ram_block1a_27.port_a_data_width = 1,
		ram_block1a_27.port_a_first_address = 0,
		ram_block1a_27.port_a_first_bit_number = 27,
		ram_block1a_27.port_a_last_address = 255,
		ram_block1a_27.port_a_logical_ram_depth = 256,
		ram_block1a_27.port_a_logical_ram_width = 32,
		ram_block1a_27.port_b_address_clear = "none",
		ram_block1a_27.port_b_address_clock = "clock1",
		ram_block1a_27.port_b_address_width = 8,
		ram_block1a_27.port_b_data_out_clear = "clear0",
		ram_block1a_27.port_b_data_width = 1,
		ram_block1a_27.port_b_first_address = 0,
		ram_block1a_27.port_b_first_bit_number = 27,
		ram_block1a_27.port_b_last_address = 255,
		ram_block1a_27.port_b_logical_ram_depth = 256,
		ram_block1a_27.port_b_logical_ram_width = 32,
		ram_block1a_27.port_b_read_enable_clock = "clock1",
		ram_block1a_27.power_up_uninitialized = "true",
		ram_block1a_27.ram_block_type = "AUTO",
		ram_block1a_27.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_28
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[3]}),
	.portadatain({data_a[28]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_28portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_28.clk0_core_clock_enable = "ena0",
		ram_block1a_28.clk0_input_clock_enable = "none",
		ram_block1a_28.clk1_core_clock_enable = "ena1",
		ram_block1a_28.clk1_input_clock_enable = "none",
		ram_block1a_28.connectivity_checking = "OFF",
		ram_block1a_28.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_28.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_28.operation_mode = "dual_port",
		ram_block1a_28.port_a_address_width = 8,
		ram_block1a_28.port_a_byte_enable_mask_width = 1,
		ram_block1a_28.port_a_byte_size = 1,
		ram_block1a_28.port_a_data_width = 1,
		ram_block1a_28.port_a_first_address = 0,
		ram_block1a_28.port_a_first_bit_number = 28,
		ram_block1a_28.port_a_last_address = 255,
		ram_block1a_28.port_a_logical_ram_depth = 256,
		ram_block1a_28.port_a_logical_ram_width = 32,
		ram_block1a_28.port_b_address_clear = "none",
		ram_block1a_28.port_b_address_clock = "clock1",
		ram_block1a_28.port_b_address_width = 8,
		ram_block1a_28.port_b_data_out_clear = "clear0",
		ram_block1a_28.port_b_data_width = 1,
		ram_block1a_28.port_b_first_address = 0,
		ram_block1a_28.port_b_first_bit_number = 28,
		ram_block1a_28.port_b_last_address = 255,
		ram_block1a_28.port_b_logical_ram_depth = 256,
		ram_block1a_28.port_b_logical_ram_width = 32,
		ram_block1a_28.port_b_read_enable_clock = "clock1",
		ram_block1a_28.power_up_uninitialized = "true",
		ram_block1a_28.ram_block_type = "AUTO",
		ram_block1a_28.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_29
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[3]}),
	.portadatain({data_a[29]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_29portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_29.clk0_core_clock_enable = "ena0",
		ram_block1a_29.clk0_input_clock_enable = "none",
		ram_block1a_29.clk1_core_clock_enable = "ena1",
		ram_block1a_29.clk1_input_clock_enable = "none",
		ram_block1a_29.connectivity_checking = "OFF",
		ram_block1a_29.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_29.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_29.operation_mode = "dual_port",
		ram_block1a_29.port_a_address_width = 8,
		ram_block1a_29.port_a_byte_enable_mask_width = 1,
		ram_block1a_29.port_a_byte_size = 1,
		ram_block1a_29.port_a_data_width = 1,
		ram_block1a_29.port_a_first_address = 0,
		ram_block1a_29.port_a_first_bit_number = 29,
		ram_block1a_29.port_a_last_address = 255,
		ram_block1a_29.port_a_logical_ram_depth = 256,
		ram_block1a_29.port_a_logical_ram_width = 32,
		ram_block1a_29.port_b_address_clear = "none",
		ram_block1a_29.port_b_address_clock = "clock1",
		ram_block1a_29.port_b_address_width = 8,
		ram_block1a_29.port_b_data_out_clear = "clear0",
		ram_block1a_29.port_b_data_width = 1,
		ram_block1a_29.port_b_first_address = 0,
		ram_block1a_29.port_b_first_bit_number = 29,
		ram_block1a_29.port_b_last_address = 255,
		ram_block1a_29.port_b_logical_ram_depth = 256,
		ram_block1a_29.port_b_logical_ram_width = 32,
		ram_block1a_29.port_b_read_enable_clock = "clock1",
		ram_block1a_29.power_up_uninitialized = "true",
		ram_block1a_29.ram_block_type = "AUTO",
		ram_block1a_29.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_30
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[3]}),
	.portadatain({data_a[30]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_30portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_30.clk0_core_clock_enable = "ena0",
		ram_block1a_30.clk0_input_clock_enable = "none",
		ram_block1a_30.clk1_core_clock_enable = "ena1",
		ram_block1a_30.clk1_input_clock_enable = "none",
		ram_block1a_30.connectivity_checking = "OFF",
		ram_block1a_30.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_30.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_30.operation_mode = "dual_port",
		ram_block1a_30.port_a_address_width = 8,
		ram_block1a_30.port_a_byte_enable_mask_width = 1,
		ram_block1a_30.port_a_byte_size = 1,
		ram_block1a_30.port_a_data_width = 1,
		ram_block1a_30.port_a_first_address = 0,
		ram_block1a_30.port_a_first_bit_number = 30,
		ram_block1a_30.port_a_last_address = 255,
		ram_block1a_30.port_a_logical_ram_depth = 256,
		ram_block1a_30.port_a_logical_ram_width = 32,
		ram_block1a_30.port_b_address_clear = "none",
		ram_block1a_30.port_b_address_clock = "clock1",
		ram_block1a_30.port_b_address_width = 8,
		ram_block1a_30.port_b_data_out_clear = "clear0",
		ram_block1a_30.port_b_data_width = 1,
		ram_block1a_30.port_b_first_address = 0,
		ram_block1a_30.port_b_first_bit_number = 30,
		ram_block1a_30.port_b_last_address = 255,
		ram_block1a_30.port_b_logical_ram_depth = 256,
		ram_block1a_30.port_b_logical_ram_width = 32,
		ram_block1a_30.port_b_read_enable_clock = "clock1",
		ram_block1a_30.power_up_uninitialized = "true",
		ram_block1a_30.ram_block_type = "AUTO",
		ram_block1a_30.lpm_type = "fiftyfivenm_ram_block";
	fiftyfivenm_ram_block   ram_block1a_31
	( 
	.clk0(clock0),
	.clk1(clock0),
	.clr0(aclr0),
	.ena0(wren_a),
	.ena1((rden_b_store | rden_b)),
	.portaaddr({address_a_wire[7:0]}),
	.portabyteenamasks({byteena_a[3]}),
	.portadatain({data_a[31]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdataout(wire_ram_block1a_31portbdataout[0:0]),
	.portbre(rden_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr1(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portare(1'b1),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_31.clk0_core_clock_enable = "ena0",
		ram_block1a_31.clk0_input_clock_enable = "none",
		ram_block1a_31.clk1_core_clock_enable = "ena1",
		ram_block1a_31.clk1_input_clock_enable = "none",
		ram_block1a_31.connectivity_checking = "OFF",
		ram_block1a_31.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_31.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_31.operation_mode = "dual_port",
		ram_block1a_31.port_a_address_width = 8,
		ram_block1a_31.port_a_byte_enable_mask_width = 1,
		ram_block1a_31.port_a_byte_size = 1,
		ram_block1a_31.port_a_data_width = 1,
		ram_block1a_31.port_a_first_address = 0,
		ram_block1a_31.port_a_first_bit_number = 31,
		ram_block1a_31.port_a_last_address = 255,
		ram_block1a_31.port_a_logical_ram_depth = 256,
		ram_block1a_31.port_a_logical_ram_width = 32,
		ram_block1a_31.port_b_address_clear = "none",
		ram_block1a_31.port_b_address_clock = "clock1",
		ram_block1a_31.port_b_address_width = 8,
		ram_block1a_31.port_b_data_out_clear = "clear0",
		ram_block1a_31.port_b_data_width = 1,
		ram_block1a_31.port_b_first_address = 0,
		ram_block1a_31.port_b_first_bit_number = 31,
		ram_block1a_31.port_b_last_address = 255,
		ram_block1a_31.port_b_logical_ram_depth = 256,
		ram_block1a_31.port_b_logical_ram_width = 32,
		ram_block1a_31.port_b_read_enable_clock = "clock1",
		ram_block1a_31.power_up_uninitialized = "true",
		ram_block1a_31.ram_block_type = "AUTO",
		ram_block1a_31.lpm_type = "fiftyfivenm_ram_block";
	assign
		address_a_wire = address_a,
		address_b_wire = address_b,
		q_b = {wire_ram_block1a_31portbdataout[0], wire_ram_block1a_30portbdataout[0], wire_ram_block1a_29portbdataout[0], wire_ram_block1a_28portbdataout[0], wire_ram_block1a_27portbdataout[0], wire_ram_block1a_26portbdataout[0], wire_ram_block1a_25portbdataout[0], wire_ram_block1a_24portbdataout[0], wire_ram_block1a_23portbdataout[0], wire_ram_block1a_22portbdataout[0], wire_ram_block1a_21portbdataout[0], wire_ram_block1a_20portbdataout[0], wire_ram_block1a_19portbdataout[0], wire_ram_block1a_18portbdataout[0], wire_ram_block1a_17portbdataout[0], wire_ram_block1a_16portbdataout[0], wire_ram_block1a_15portbdataout[0], wire_ram_block1a_14portbdataout[0], wire_ram_block1a_13portbdataout[0], wire_ram_block1a_12portbdataout[0], wire_ram_block1a_11portbdataout[0], wire_ram_block1a_10portbdataout[0], wire_ram_block1a_9portbdataout[0], wire_ram_block1a_8portbdataout[0], wire_ram_block1a_7portbdataout[0], wire_ram_block1a_6portbdataout[0], wire_ram_block1a_5portbdataout[0], wire_ram_block1a_4portbdataout[0], wire_ram_block1a_3portbdataout[0], wire_ram_block1a_2portbdataout[0], wire_ram_block1a_1portbdataout[0], wire_ram_block1a_0portbdataout[0]};
endmodule //ram256_altsyncram
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module ram256 (
	aclr,
	byteena_a,
	clock,
	data,
	rdaddress,
	rden,
	wraddress,
	wren,
	q)/* synthesis synthesis_clearbox = 1 */;

	input	  aclr;
	input	[3:0]  byteena_a;
	input	  clock;
	input	[31:0]  data;
	input	[7:0]  rdaddress;
	input	  rden;
	input	[7:0]  wraddress;
	input	  wren;
	output	[31:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0	  aclr;
	tri1	[3:0]  byteena_a;
	tri1	  clock;
	tri1	  rden;
	tri0	  wren;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire [31:0] sub_wire0;
	wire [31:0] q = sub_wire0[31:0];

	ram256_altsyncram	ram256_altsyncram_component (
				.aclr0 (aclr),
				.address_a (wraddress),
				.address_b (rdaddress),
				.byteena_a (byteena_a),
				.clock0 (clock),
				.data_a (data),
				.rden_b (rden),
				.wren_a (wren),
				.q_b (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ADDRESSSTALL_A NUMERIC "0"
// Retrieval info: PRIVATE: ADDRESSSTALL_B NUMERIC "0"
// Retrieval info: PRIVATE: BYTEENA_ACLR_A NUMERIC "0"
// Retrieval info: PRIVATE: BYTEENA_ACLR_B NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_ENABLE_A NUMERIC "1"
// Retrieval info: PRIVATE: BYTE_ENABLE_B NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_SIZE NUMERIC "8"
// Retrieval info: PRIVATE: BlankMemory NUMERIC "1"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_B NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_B NUMERIC "0"
// Retrieval info: PRIVATE: CLRdata NUMERIC "0"
// Retrieval info: PRIVATE: CLRq NUMERIC "0"
// Retrieval info: PRIVATE: CLRrdaddress NUMERIC "0"
// Retrieval info: PRIVATE: CLRrren NUMERIC "0"
// Retrieval info: PRIVATE: CLRwraddress NUMERIC "0"
// Retrieval info: PRIVATE: CLRwren NUMERIC "0"
// Retrieval info: PRIVATE: Clock NUMERIC "0"
// Retrieval info: PRIVATE: Clock_A NUMERIC "0"
// Retrieval info: PRIVATE: Clock_B NUMERIC "0"
// Retrieval info: PRIVATE: IMPLEMENT_IN_LES NUMERIC "0"
// Retrieval info: PRIVATE: INDATA_ACLR_B NUMERIC "0"
// Retrieval info: PRIVATE: INDATA_REG_B NUMERIC "0"
// Retrieval info: PRIVATE: INIT_FILE_LAYOUT STRING "PORT_B"
// Retrieval info: PRIVATE: INIT_TO_SIM_X NUMERIC "1"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "MAX 10"
// Retrieval info: PRIVATE: JTAG_ENABLED NUMERIC "0"
// Retrieval info: PRIVATE: JTAG_ID STRING "NONE"
// Retrieval info: PRIVATE: MAXIMUM_DEPTH NUMERIC "0"
// Retrieval info: PRIVATE: MEMSIZE NUMERIC "8192"
// Retrieval info: PRIVATE: MEM_IN_BITS NUMERIC "0"
// Retrieval info: PRIVATE: MIFfilename STRING "ram256.mif"
// Retrieval info: PRIVATE: OPERATION_MODE NUMERIC "2"
// Retrieval info: PRIVATE: OUTDATA_ACLR_B NUMERIC "1"
// Retrieval info: PRIVATE: OUTDATA_REG_B NUMERIC "0"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: READ_DURING_WRITE_MODE_MIXED_PORTS NUMERIC "2"
// Retrieval info: PRIVATE: READ_DURING_WRITE_MODE_PORT_A NUMERIC "3"
// Retrieval info: PRIVATE: READ_DURING_WRITE_MODE_PORT_B NUMERIC "3"
// Retrieval info: PRIVATE: REGdata NUMERIC "1"
// Retrieval info: PRIVATE: REGq NUMERIC "0"
// Retrieval info: PRIVATE: REGrdaddress NUMERIC "1"
// Retrieval info: PRIVATE: REGrren NUMERIC "1"
// Retrieval info: PRIVATE: REGwraddress NUMERIC "1"
// Retrieval info: PRIVATE: REGwren NUMERIC "1"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: USE_DIFF_CLKEN NUMERIC "0"
// Retrieval info: PRIVATE: UseDPRAM NUMERIC "1"
// Retrieval info: PRIVATE: VarWidth NUMERIC "0"
// Retrieval info: PRIVATE: WIDTH_READ_A NUMERIC "32"
// Retrieval info: PRIVATE: WIDTH_READ_B NUMERIC "32"
// Retrieval info: PRIVATE: WIDTH_WRITE_A NUMERIC "32"
// Retrieval info: PRIVATE: WIDTH_WRITE_B NUMERIC "32"
// Retrieval info: PRIVATE: WRADDR_ACLR_B NUMERIC "0"
// Retrieval info: PRIVATE: WRADDR_REG_B NUMERIC "0"
// Retrieval info: PRIVATE: WRCTRL_ACLR_B NUMERIC "0"
// Retrieval info: PRIVATE: enable NUMERIC "0"
// Retrieval info: PRIVATE: rden NUMERIC "1"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: ADDRESS_ACLR_B STRING "NONE"
// Retrieval info: CONSTANT: ADDRESS_REG_B STRING "CLOCK0"
// Retrieval info: CONSTANT: BYTE_SIZE NUMERIC "8"
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_B STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_OUTPUT_B STRING "BYPASS"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "MAX 10"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altsyncram"
// Retrieval info: CONSTANT: NUMWORDS_A NUMERIC "256"
// Retrieval info: CONSTANT: NUMWORDS_B NUMERIC "256"
// Retrieval info: CONSTANT: OPERATION_MODE STRING "DUAL_PORT"
// Retrieval info: CONSTANT: OUTDATA_ACLR_B STRING "CLEAR0"
// Retrieval info: CONSTANT: OUTDATA_REG_B STRING "UNREGISTERED"
// Retrieval info: CONSTANT: POWER_UP_UNINITIALIZED STRING "TRUE"
// Retrieval info: CONSTANT: RDCONTROL_REG_B STRING "CLOCK0"
// Retrieval info: CONSTANT: READ_DURING_WRITE_MODE_MIXED_PORTS STRING "DONT_CARE"
// Retrieval info: CONSTANT: WIDTHAD_A NUMERIC "8"
// Retrieval info: CONSTANT: WIDTHAD_B NUMERIC "8"
// Retrieval info: CONSTANT: WIDTH_A NUMERIC "32"
// Retrieval info: CONSTANT: WIDTH_B NUMERIC "32"
// Retrieval info: CONSTANT: WIDTH_BYTEENA_A NUMERIC "4"
// Retrieval info: USED_PORT: aclr 0 0 0 0 INPUT GND "aclr"
// Retrieval info: USED_PORT: byteena_a 0 0 4 0 INPUT VCC "byteena_a[3..0]"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT VCC "clock"
// Retrieval info: USED_PORT: data 0 0 32 0 INPUT NODEFVAL "data[31..0]"
// Retrieval info: USED_PORT: q 0 0 32 0 OUTPUT NODEFVAL "q[31..0]"
// Retrieval info: USED_PORT: rdaddress 0 0 8 0 INPUT NODEFVAL "rdaddress[7..0]"
// Retrieval info: USED_PORT: rden 0 0 0 0 INPUT VCC "rden"
// Retrieval info: USED_PORT: wraddress 0 0 8 0 INPUT NODEFVAL "wraddress[7..0]"
// Retrieval info: USED_PORT: wren 0 0 0 0 INPUT GND "wren"
// Retrieval info: CONNECT: @aclr0 0 0 0 0 aclr 0 0 0 0
// Retrieval info: CONNECT: @address_a 0 0 8 0 wraddress 0 0 8 0
// Retrieval info: CONNECT: @address_b 0 0 8 0 rdaddress 0 0 8 0
// Retrieval info: CONNECT: @byteena_a 0 0 4 0 byteena_a 0 0 4 0
// Retrieval info: CONNECT: @clock0 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: @data_a 0 0 32 0 data 0 0 32 0
// Retrieval info: CONNECT: @rden_b 0 0 0 0 rden 0 0 0 0
// Retrieval info: CONNECT: @wren_a 0 0 0 0 wren 0 0 0 0
// Retrieval info: CONNECT: q 0 0 32 0 @q_b 0 0 32 0
// Retrieval info: GEN_FILE: TYPE_NORMAL ram256.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL ram256.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL ram256.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL ram256.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL ram256_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL ram256_bb.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL ram256_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
